### PR TITLE
Fixes to Fastino V1.0

### PR DESCRIPTION
**Pull request by pathfinder49**
I've addressed all issues with V1.0 I'm aware of. Specifically I've done addressed issues:
1. Fixed the DAC resistor package routing (discussed in #42)
2. Connected P3V3_MP to the EEM cables #47 
3. Fixed the circular i2c dependecy and R48 #48 
4. Grounded IC3 housing #53
5. Increased P/N12V0A capacitance 3-fold (#54 & #69)
6. Add 62 ohm series termination and change parallel termination to 15 pF, 0603 capacitors (not yet DNP) #63
7. Rerouted digital and analogue DAC traces #64 
8. Removed CMCs #65
9. Reduced polygon-via clearance #67

I still need to figure out how to mark the parallel termination capacitors as DNP. I'm also unsure if component clearances may pose a problem (design rules pass).

@gkasprow Could you please review my changes?

### CODE REVIEW

**Comment by gkasprow** [comment]
@pathfinder49 use variants to mark components as DNP

**Comment by gkasprow** [comment]
all components have a dedicated layer (M15) which can be used as a clearance indicator

**Comment by pathfinder49** [comment]
> 
> 
> all components have a dedicated layer (M15) which can be used as a clearance indicator

Are these minium requirements?

**Comment by hartytp** [comment]
Ace, thanks @pathfinder49 !

@gkasprow are you okay to do a careful review of the new layout, paying close attention to SI and cross-talk? Once that's done I'd love to get a new batch into production

**Comment by hartytp** [comment]
@pathfinder49 btw https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords is a really nice feature to ensure the resolved issues get closed automatically when the PR is merged.

**Comment by pathfinder49** [comment]
> 
> 
> all components have a dedicated layer (M15) which can be used as a clearance indicator

@gkasprow The component clearences inbdicated on M15 tend to be rectangular. This does not match the actual component shpes. For example: the the 16 DAC pins leave the corners of the DAC clearance box physically un-occupied. Are these **required** to be unoccupieed?

**Comment by pathfinder49** [comment]
@gkasprow Hope you're doing well. When you have a chance, could please you take a look at my changes?

**Comment by pathfinder49** [comment]
https://github.com/sinara-hw/Fastino/issues/72#issuecomment-617446463
> 
> I think it is good enough. Every project can be done better, but here the main goal is high channel isolation. Let's produce it;

@gkasprow @cjbe @hartytp Could one of you please merge this?

**Comment by gkasprow** [comment]
I prefer to do it from my computer.

**Comment by hartytp** [comment]
Did this get merged? Should we close now?

**Comment by pathfinder49** [comment]
> 
> 
> Did this get merged? Should we close now?

I believe @gkasprow didn't merge this, but re-comitted and pushed the final state to master.

**Comment by hartytp** [comment]
@pathfinder49 my understanding is that all the work in this PR made its way into v1.1 so it's safe to close the PR. Please re-open if that's not the case.

**Pull request closed without merging**
